---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для
    скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность сделать заказ
  - Пользователь должен иметь возможность оплатить товар
  - Пользователь должен иметь возможность увидеть цену товара в долларах и в
    рублях?
  - Пользователь должен иметь возможность сбрасывать фильтр товаров
  - Сайт должен быть доступен на нескольких языках
  - Пользователь должен иметь возможность видеть в корзине цену за единицу товара
  - Пользователь должен иметь возможность видеть товары из наличии
  - магазин должен работать как SPA-приложение
